### ISSUE TITLE
AWS Provider >=3.0.0 ASG inline load_balancers removing attached load balancers

### ISSUE THREAD

**Issue by andrew-womeldorf** [hashicorp/terraform-aws-vault#210] opened 2020-08-15 21:38 UTC
Since the AWS Provider's update to v3.0.0, the relationship between an `aws_autoscaling_group` and `aws_autoscaling_attachment` has become more strictly conflicted. Since the `vault-cluster` module does not define a load balancer, and a load balancer must be attached by an autoscaling attachment from outside the `vault-cluster` module, the autoscaling groups should ignore changes to the `load_balancers` and `target_group_arns`.

In my case, despite the `vault-elb` module defining the autoscaling attachment, the AWS provider is trying to remove the relationship in favor of the empty inline `load_balancers` argument. There is a similar issue in the `terraform-aws-consul` module.

This conflict is documented in the AWS Provider's documentation [here](https://registry.terraform.io/providers/hashicorp/aws/3.0.0/docs/resources/autoscaling_attachment), and there is [an open issue](https://github.com/terraform-providers/terraform-provider-aws/issues/14540) on the AWS Provider repo.

**Comment by brikis98** [comment] 2020-08-17 07:25
> This conflict is documented in the AWS Provider's documentation [here](https://registry.terraform.io/providers/hashicorp/aws/3.0.0/docs/resources/autoscaling_attachment), and there is [an open issue](https://github.com/terraform-providers/terraform-provider-aws/issues/14540) on the AWS Provider repo.

So is this actually a bug we should wait to be fixed? And perhaps pin to AWS Provider < 3.x until it is fixed?

**Comment by andrew-womeldorf** [comment] 2020-08-17 14:14
The issue I linked is only a week old, so it may be too soon to tell if it's planned on being fixed.

My personal impression is that this is not going to be fixed soon. This was already [a documented issue in 2.x](https://registry.terraform.io/providers/hashicorp/aws/2.70.0/docs/resources/autoscaling_attachment). It seems that the inline `load_balancers`/`target_group_arns` weren't actively overriding the `aws_autoscaling_attachment` resource in 2.x like they are now.

**Comment by teraflik** [comment] 2020-09-07 13:07
> > This conflict is documented in the AWS Provider's documentation [here](https://registry.terraform.io/providers/hashicorp/aws/3.0.0/docs/resources/autoscaling_attachment), and there is [an open issue](https://github.com/terraform-providers/terraform-provider-aws/issues/14540) on the AWS Provider repo.
> 
> So is this actually a bug we should wait to be fixed? And perhaps pin to AWS Provider < 3.x until it is fixed?

@brikis98 this is not a bug, it is an intended behaviour when using AWS Provider ~ 3.x. 

As the documentation mentions everywhere, using same of the inline resource and exclusive resource "[causes conflicts](https://registry.terraform.io/providers/hashicorp/aws/2.70.0/docs/resources/autoscaling_attachment)" or  "[unintended resource updates](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_attachment)".

I can't comment why it didn't cause problems in AWS provider ~ 2.x, but with provider ~ 3.x, it's working as it should (by causing problems.) 

As @andrew-womeldorf said, its a safe assumption that an ASG will either be used with a target group or a load balancer, for example in the [vault-elb module](https://github.com/hashicorp/terraform-aws-vault/blob/master/modules/vault-elb/main.tf#L49-L56). I think we should add this lifecycle configuration block in the ASG resource to fix this issue:

```
lifecycle {
    ignore_changes = [load_balancers, target_group_arns]
  }
```

**Comment by brikis98** [comment] 2020-09-11 07:22
Roger. Hopefully we can get #211 merged soon to fix this.

**Closed** 2020-09-13 13:19 UTC
Labels: enhancement, help wanted
